# Generated by Django 5.0.2 on 2024-03-02 19:10

import gdstorage.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReceiveOSP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="Fecha"
                    ),
                ),
                (
                    "time",
                    models.TimeField(auto_now_add=True, null=True, verbose_name="Hora"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("Unpaid", "Unpaid"), ("Paid", "Paid")],
                        default="Unpaid",
                        max_length=13,
                        verbose_name="Estado de la orden",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=11,
                        verbose_name="Monto a pagar",
                    ),
                ),
                ("code", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=gdstorage.storage.GoogleDriveStorage(),
                        upload_to="avatar/",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recibir OSP",
                "verbose_name_plural": "Recibir OSP",
            },
        ),
        migrations.CreateModel(
            name="TransferManagerOrderUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="Fecha"
                    ),
                ),
                (
                    "time",
                    models.TimeField(auto_now_add=True, null=True, verbose_name="Hora"),
                ),
                (
                    "cant_zona_point",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Puntos de Zona0 transferidos",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=50,
                        verbose_name="Correo Electrónico del usuario al que se le transfirió",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Transferencia", "Transferencia"),
                            ("Quema", "Quema"),
                        ],
                        default="Transferencia",
                        max_length=13,
                        verbose_name="Tipo de orden",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recarga a usuario",
                "verbose_name_plural": "Recargas a usuarios",
            },
        ),
        migrations.CreateModel(
            name="TransferOSP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="Fecha"
                    ),
                ),
                (
                    "time",
                    models.TimeField(auto_now_add=True, null=True, verbose_name="Hora"),
                ),
            ],
            options={
                "verbose_name": "Enviar OSP",
                "verbose_name_plural": "Enviar OSP",
            },
        ),
    ]
