# Generated by Django 4.2.7 on 2023-11-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transferorderusers",
            options={
                "verbose_name": "Transferencia de usuario",
                "verbose_name_plural": "Transferencias de usuarios",
            },
        ),
        migrations.AlterField(
            model_name="transferorderusers",
            name="email",
            field=models.EmailField(
                max_length=50,
                verbose_name="Correo Electrónico del usuario al que se le transfirió",
            ),
        ),
    ]
