# Generated by Django 4.2.7 on 2023-11-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_transferorderusers_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferorderusers",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True,
                null=True,
                verbose_name="Fecha y hora de efectuada la transferencia",
            ),
        ),
    ]
