# Generated by Django 4.2.7 on 2023-11-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_transferorderusers_creation_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transferorderusers",
            name="creation_date",
        ),
        migrations.AddField(
            model_name="transferorderusers",
            name="date",
            field=models.DateField(
                auto_now_add=True,
                null=True,
                verbose_name="Fecha deefectuada la transferencia",
            ),
        ),
        migrations.AddField(
            model_name="transferorderusers",
            name="time",
            field=models.TimeField(
                auto_now_add=True,
                null=True,
                verbose_name="Hora de efectuada la transferencia",
            ),
        ),
    ]
