# Generated by Django 4.2.7 on 2023-11-22 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_alter_user_last_name_alter_user_name"),
        ("orders", "0004_remove_transferorderusers_creation_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferManagerOrderUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Fecha deefectuada la transferencia",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Hora de efectuada la transferencia",
                    ),
                ),
                (
                    "cant_zona_point",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Puntos de Zona0 transferidos",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=50,
                        verbose_name="Correo Electrónico del usuario al que se le transfirió",
                    ),
                ),
                (
                    "user_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.zona0manager",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recarga a usuario",
                "verbose_name_plural": "Recargas a usuarios",
            },
        ),
    ]
