# Generated by Django 4.2.7 on 2023-11-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_transfermanagerorderusers"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfermanagerorderusers",
            name="type",
            field=models.CharField(
                choices=[("Transferencia", "Transferencia"), ("Quema", "Quema")],
                default="Transferencia",
                max_length=13,
                verbose_name="Tipo de orden",
            ),
        ),
    ]
