# Generated by Django 4.2.7 on 2024-01-08 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0006_transfermanagerorderusers_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiveOSP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("Unpaid", "Unpaid"), ("Paid", "Paid")],
                        default="Unpaid",
                        max_length=13,
                        verbose_name="Estado de la orden",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=11,
                        verbose_name="Monto a pagar",
                    ),
                ),
                ("code", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=gdstorage.storage.GoogleDriveStorage(),
                        upload_to="code/",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recibir OSP",
                "verbose_name_plural": "Recibir OSP",
            },
        ),
        migrations.CreateModel(
            name="TransferOSP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Fecha de efectuada la transferencia",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Hora de efectuada la transferencia",
                    ),
                ),
                (
                    "cant_zona_point",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Puntos de Zona0 transferidos",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=50,
                        verbose_name="Correo Electrónico del usuario al que se le transfirió",
                    ),
                ),
                (
                    "receive",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.receiveosp",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recibir OSP",
                "verbose_name_plural": "Recibir OSP",
            },
        ),
        migrations.AlterField(
            model_name="transfermanagerorderusers",
            name="date",
            field=models.DateField(
                auto_now_add=True,
                null=True,
                verbose_name="Fecha de efectuada la transferencia",
            ),
        ),
        migrations.DeleteModel(
            name="TransferOrderUsers",
        ),
    ]
