# Generated by Django 4.2.7 on 2024-01-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_alter_receiveosp_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiveosp",
            name="date",
            field=models.DateField(
                auto_now_add=True,
                null=True,
                verbose_name="Fecha de efectuada la transferencia",
            ),
        ),
        migrations.AddField(
            model_name="receiveosp",
            name="time",
            field=models.TimeField(
                auto_now_add=True,
                null=True,
                verbose_name="Hora de efectuada la transferencia",
            ),
        ),
    ]
