# Generated by Django 4.2.7 on 2024-01-15 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_receiveosp_date_receiveosp_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transferosp",
            options={"verbose_name": "Enviar OSP", "verbose_name_plural": "Enviar OSP"},
        ),
        migrations.RemoveField(
            model_name="transferosp",
            name="cant_zona_point",
        ),
        migrations.RemoveField(
            model_name="transferosp",
            name="email",
        ),
    ]
