# Generated by Django 4.2.7 on 2024-01-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0010_alter_transferosp_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiveosp",
            name="date",
            field=models.DateField(auto_now_add=True, null=True, verbose_name="Fecha"),
        ),
        migrations.AlterField(
            model_name="receiveosp",
            name="time",
            field=models.TimeField(auto_now_add=True, null=True, verbose_name="Hora"),
        ),
        migrations.AlterField(
            model_name="transfermanagerorderusers",
            name="date",
            field=models.DateField(auto_now_add=True, null=True, verbose_name="Fecha"),
        ),
        migrations.AlterField(
            model_name="transfermanagerorderusers",
            name="time",
            field=models.TimeField(auto_now_add=True, null=True, verbose_name="Hora"),
        ),
        migrations.AlterField(
            model_name="transferosp",
            name="date",
            field=models.DateField(auto_now_add=True, null=True, verbose_name="Fecha"),
        ),
        migrations.AlterField(
            model_name="transferosp",
            name="time",
            field=models.TimeField(auto_now_add=True, null=True, verbose_name="Hora"),
        ),
    ]
