# Generated by Django 4.2.7 on 2024-01-22 20:23

import django.core.validators
from django.db import migrations, models
import utils.validates.validates


class Migration(migrations.Migration):
    dependencies = [
        ("redeem", "0002_alter_marketingapplican_prize_fund"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketingapplican",
            name="place",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    utils.validates.validates.validate_letters_numbers_and_spaces,
                ],
                verbose_name="A quién se vendio",
            ),
        ),
    ]
