# Generated by Django 4.2.7 on 2024-01-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("redeem", "0003_alter_marketingapplican_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketingapplican",
            name="cant_codes",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Cantidad de codigos"
            ),
        ),
    ]
