# Generated by Django 4.2.7 on 2024-01-23 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("redeem", "0004_marketingapplican_cant_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketingapplican",
            name="cant_codes",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Cantidad de codigos",
            ),
        ),
        migrations.AlterField(
            model_name="marketingapplican",
            name="date",
            field=models.DateField(auto_now_add=True, null=True, verbose_name="Fecha"),
        ),
        migrations.AlterField(
            model_name="marketingapplican",
            name="prize_fund",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=11,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Fondo de premio",
            ),
        ),
        migrations.AlterField(
            model_name="marketingapplican",
            name="time",
            field=models.TimeField(auto_now_add=True, null=True, verbose_name="Hora"),
        ),
        migrations.AlterField(
            model_name="marketingapplican",
            name="winners",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Cantidad de premiados",
            ),
        ),
    ]
