# Generated by Django 5.0.2 on 2024-03-02 19:10

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pin", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "min_withdraw",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=11,
                        verbose_name="Minimo diario a extraer",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Tarjeta activa"),
                ),
                (
                    "on_hold",
                    models.BooleanField(default=False, verbose_name="En espera"),
                ),
                (
                    "discount_code",
                    models.CharField(
                        default="0A1A2A",
                        max_length=6,
                        validators=[django.core.validators.MinLengthValidator(6)],
                        verbose_name="Código de descuento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarjeta OS",
                "verbose_name_plural": "Tarjetas OS",
            },
        ),
        migrations.CreateModel(
            name="DiscountCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="Fecha"
                    ),
                ),
                (
                    "time",
                    models.TimeField(auto_now_add=True, null=True, verbose_name="Hora"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=11,
                        verbose_name="Descuento de OSP",
                    ),
                ),
            ],
            options={
                "verbose_name": "Descuento Tarjeta OS",
                "verbose_name_plural": "Descuentos Tarjetas OS",
            },
        ),
    ]
