# Generated by Django 4.2.7 on 2024-01-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("card", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="on_hold",
            field=models.BooleanField(default=False, verbose_name="En espera"),
        ),
    ]
