# Generated by Django 4.2.7 on 2024-01-31 23:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("card", "0002_card_on_hold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="discount_code",
            field=models.CharField(
                default="0A1A2A",
                max_length=6,
                validators=[django.core.validators.MinLengthValidator(6)],
                verbose_name="Código de descuento",
            ),
        ),
    ]
