# Generated by Django 4.2.7 on 2024-01-21 17:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage
import utils.validates.validates


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institution_name",
                    models.CharField(
                        max_length=75,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            utils.validates.validates.validate_letters_numbers_and_spaces,
                        ],
                        verbose_name="Nombre de Enmpresa",
                    ),
                ),
                (
                    "institution_osp",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=11,
                        verbose_name="Monto a pagar",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=500,
                        validators=[
                            utils.validates.validates.validate_letters_numbers_and_spaces
                        ],
                        verbose_name="Descripción de la institución",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=gdstorage.storage.GoogleDriveStorage(),
                        upload_to="avatar/",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Institucion",
                "verbose_name_plural": "Instituciones",
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=gdstorage.storage.GoogleDriveStorage(),
                        upload_to="avatar/",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=100,
                        validators=[
                            utils.validates.validates.validate_letters_numbers_and_spaces
                        ],
                        verbose_name="Descripción de la imagen",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="institution.institution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Galeria de institucion",
                "verbose_name_plural": "Galeria de instituciones",
            },
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Fecha de efectuada la transferencia",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Hora de efectuada la transferencia",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=11,
                        verbose_name="Monto a donar",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="institution.institution",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Donacion",
                "verbose_name_plural": "Donaciones",
            },
        ),
    ]
