# Generated by Django 5.0.2 on 2024-03-02 19:10

import django.core.validators
import gdstorage.storage
import utils.validates.validates
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="Fecha"
                    ),
                ),
                (
                    "time",
                    models.TimeField(auto_now_add=True, null=True, verbose_name="Hora"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=11,
                        verbose_name="Monto a donar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donacion",
                "verbose_name_plural": "Donaciones",
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=gdstorage.storage.GoogleDriveStorage(),
                        upload_to="avatar/",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=100,
                        validators=[
                            utils.validates.validates.validate_letters_numbers_and_spaces
                        ],
                        verbose_name="Descripción de la imagen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Galeria de institucion",
                "verbose_name_plural": "Galeria de instituciones",
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institution_name",
                    models.CharField(
                        max_length=75,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            utils.validates.validates.validate_letters_numbers_and_spaces,
                        ],
                        verbose_name="Nombre de Enmpresa",
                    ),
                ),
                (
                    "institution_osp",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=11,
                        verbose_name="Donaciones en OSP",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Descripción de la institución",
                        verbose_name="Descripción de la institución",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=gdstorage.storage.GoogleDriveStorage(),
                        upload_to="avatar/",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Institucion",
                "verbose_name_plural": "Instituciones",
            },
        ),
    ]
