# Generated by Django 4.2.7 on 2024-01-21 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="galleryInstitution",
                to="institution.institution",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="institution_osp",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=11,
                verbose_name="Donaciones en OSP",
            ),
        ),
    ]
