# Generated by Django 4.2.7 on 2024-01-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0002_alter_gallery_institution_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="date",
            field=models.DateField(auto_now_add=True, null=True, verbose_name="Fecha"),
        ),
        migrations.AlterField(
            model_name="donation",
            name="time",
            field=models.TimeField(auto_now_add=True, null=True, verbose_name="Hora"),
        ),
    ]
