# Generated by Django 4.2.7 on 2024-02-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0003_alter_donation_date_alter_donation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="description",
            field=models.TextField(
                default="Descripción de la institución",
                verbose_name="Descripción de la institución",
            ),
        ),
    ]
