# Generated by Django 4.2.7 on 2023-11-11 17:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from utils.validates.validates import *


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            validate_alnum,
                        ],
                        verbose_name="Nombre de Usuario",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=50, unique=True, verbose_name="Correo Electrónico"
                    ),
                ),
                (
                    "movil",
                    models.CharField(
                        max_length=8,
                        validators=[
                            django.core.validators.MinLengthValidator(8),
                            validate_digits,
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "zona_point",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Puntos de Zona0"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            validate_alpha,
                        ],
                        verbose_name="Nombres",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            validate_alpha,
                        ],
                        verbose_name="Apellidos",
                    ),
                ),
                (
                    "ci",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(11),
                            validate_digits,
                        ],
                        verbose_name="Carnet de identidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
            bases=("users.user",),
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        max_length=75,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            validate_alnum,
                        ],
                        verbose_name="Nombre de Enmpresa",
                    ),
                ),
                (
                    "company_representative",
                    models.CharField(
                        max_length=75,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            validate_alpha,
                        ],
                        verbose_name="Representante de la empresa",
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        max_length=30,
                        validators=[validate_digits],
                        verbose_name="Codigo de la empresa",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("1", "Mipyme"), ("2", "TCP"), ("3", "Estatal")],
                        max_length=1,
                        verbose_name="Tipo de empresa",
                    ),
                ),
                ("correct_company", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Compañia",
                "verbose_name_plural": "Compañias",
            },
            bases=("users.user",),
        ),
    ]
