# Generated by Django 5.0.2 on 2024-03-02 19:10

import django.core.validators
import django.db.models.deletion
import gdstorage.storage
import utils.validates.validates
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("client", "Client"), ("company", "Company")],
                        default="client",
                        max_length=10,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_alnum,
                        ],
                        verbose_name="Nombre de Usuario",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=50, unique=True, verbose_name="Correo Electrónico"
                    ),
                ),
                (
                    "movil",
                    models.CharField(
                        max_length=8,
                        validators=[
                            django.core.validators.MinLengthValidator(8),
                            utils.validates.validates.validate_digits,
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "verified_email",
                    models.BooleanField(default=False, verbose_name="Verificar email"),
                ),
                (
                    "zona_point",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                        verbose_name="Puntos de Zona0",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_letters_and_spaces,
                        ],
                        verbose_name="Nombres",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_letters_and_spaces,
                        ],
                        verbose_name="Apellidos",
                    ),
                ),
                (
                    "ci",
                    models.CharField(
                        max_length=11,
                        validators=[
                            django.core.validators.MinLengthValidator(11),
                            utils.validates.validates.validate_digits,
                        ],
                        verbose_name="Carnet de identidad",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=gdstorage.storage.GoogleDriveStorage(),
                        upload_to="avatar/",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
            bases=("users.user",),
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        max_length=75,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            utils.validates.validates.validate_letters_numbers_and_spaces,
                        ],
                        verbose_name="Nombre de Enmpresa",
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        max_length=30,
                        validators=[utils.validates.validates.validate_digits],
                        verbose_name="Codigo de la empresa",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Mipyme", "Mipyme"),
                            ("TCP", "TCP"),
                            ("Estatal", "Estatal"),
                        ],
                        max_length=7,
                        verbose_name="Tipo de empresa",
                    ),
                ),
                ("correct_company", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Compañia",
                "verbose_name_plural": "Compañias",
            },
            bases=("users.user",),
        ),
        migrations.CreateModel(
            name="Zona0Manager",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "total_recauder",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Total de puntos de Zona0 vendidos",
                    ),
                ),
                (
                    "total_burn",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Total de puntos de Zona0 quemados",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manager",
                "verbose_name_plural": "Managers",
            },
            bases=("users.user",),
        ),
    ]
