# Generated by Django 4.2.7 on 2023-11-11 19:40

import utils
import django.core.validators
from django.db import migrations, models
from utils.validates.validates import *


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_zona_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="last_name",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    validate_letters_and_spaces,
                ],
                verbose_name="Apellidos",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    validate_letters_and_spaces,
                ],
                verbose_name="Nombres",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_name",
            field=models.CharField(
                max_length=75,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    validate_letters_numbers_and_spaces,
                ],
                verbose_name="Nombre de Enmpresa",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_representative",
            field=models.CharField(
                max_length=75,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    validate_letters_and_spaces,
                ],
                verbose_name="Representante de la empresa",
            ),
        ),
    ]
