# Generated by Django 4.2.7 on 2023-11-17 17:23

import utils.validates.validates
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_client_last_name_alter_client_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zona0Manager",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_letters_and_spaces,
                        ],
                        verbose_name="Nombres manager",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_letters_and_spaces,
                        ],
                        verbose_name="Apellidos manager",
                    ),
                ),
                (
                    "ci",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(11),
                            utils.validates.validates.validate_digits,
                        ],
                        verbose_name="Carnet de identidad manager",
                    ),
                ),
                (
                    "total_recauder",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Total de puntos de Zona0 vendidos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manager",
                "verbose_name_plural": "Managers",
            },
            bases=("users.user",),
        ),
    ]
