# Generated by Django 4.2.7 on 2023-11-17 21:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_zona0manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="zona0manager",
            name="total_recauder",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Total de puntos de Zona0 vendidos",
            ),
        ),
    ]
