# Generated by Django 4.2.7 on 2023-11-17 23:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_user_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="token",
        ),
    ]
