# Generated by Django 4.2.7 on 2023-11-18 06:03

import utils.validates.validates
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_user_verified_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="ci",
        ),
        migrations.RemoveField(
            model_name="client",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="client",
            name="name",
        ),
        migrations.RemoveField(
            model_name="company",
            name="company_representative",
        ),
        migrations.RemoveField(
            model_name="zona0manager",
            name="ci",
        ),
        migrations.RemoveField(
            model_name="zona0manager",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="zona0manager",
            name="name",
        ),
        migrations.AddField(
            model_name="user",
            name="ci",
            field=models.CharField(
                default="",
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(11),
                    utils.validates.validates.validate_digits,
                ],
                verbose_name="Carnet de identidad",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                default="",
                max_length=50,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    utils.validates.validates.validate_letters_and_spaces,
                ],
                verbose_name="Apellidos",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(
                default="",
                max_length=50,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    utils.validates.validates.validate_letters_and_spaces,
                ],
                verbose_name="Nombres",
            ),
        ),
    ]
