# Generated by Django 4.2.7 on 2023-11-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_remove_client_ci_remove_client_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="type",
            field=models.CharField(
                choices=[("Mipyme", "Mipyme"), ("TCP", "TCP"), ("Estatal", "Estatal")],
                max_length=7,
                verbose_name="Tipo de empresa",
            ),
        ),
    ]
