# Generated by Django 4.2.7 on 2023-11-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_alter_user_zona_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("client", "Client"), ("company", "Company")],
                default="client",
                max_length=20,
            ),
        ),
    ]
