# Generated by Django 4.2.7 on 2023-11-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("client", "Client"), ("company", "Company")],
                default="client",
                max_length=10,
            ),
        ),
    ]
