# Generated by Django 4.2.7 on 2023-11-21 21:31

import django.core.validators
from django.db import migrations, models
import utils.validates.validates


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_alter_user_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ci",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(11),
                    utils.validates.validates.validate_digits,
                ],
                verbose_name="Carnet de identidad",
            ),
        ),
    ]
