# Generated by Django 4.2.7 on 2023-11-21 22:05

import django.core.validators
from django.db import migrations, models
import utils.validates.validates


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_alter_user_ci"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    utils.validates.validates.validate_letters_and_spaces,
                ],
                verbose_name="Apellidos",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    utils.validates.validates.validate_letters_and_spaces,
                ],
                verbose_name="Nombres",
            ),
        ),
    ]
