# Generated by Django 4.2.7 on 2023-11-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_alter_user_last_name_alter_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="zona0manager",
            name="total_burn",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Total de puntos de Zona0 vendidos",
            ),
        ),
    ]
