# Generated by Django 4.2.7 on 2023-11-26 21:57

from django.db import migrations, models
from django.contrib.auth import get_user_model


def create_user(apps,schema_editor):
    User = get_user_model()
    User.objects.create_superuser('mangel','mangelryujin@gmail.com','admin')
    

class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_zona0manager_total_burn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zona0manager",
            name="total_burn",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Total de puntos de Zona0 quemados",
            ),
        ),
        migrations.RunPython(create_user),
    ]
