# Generated by Django 4.2.7 on 2023-11-28 05:49

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_map"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvatarImageUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        storage=gdstorage.storage.GoogleDriveStorage(),
                        upload_to="avatar/",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Map",
        ),
    ]
