# Generated by Django 4.2.7 on 2023-11-28 06:14

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0026_avatarimageuser_delete_map"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to="avatar/",
            ),
        ),
    ]
