# Generated by Django 5.0.2 on 2024-03-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="Fecha"
                    ),
                ),
                (
                    "time",
                    models.TimeField(auto_now_add=True, null=True, verbose_name="Hora"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("Banked", "Banked"), ("Retired", "Retired")],
                        default="Banked",
                        max_length=10,
                        verbose_name="Estado de la bancarización",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=11,
                        verbose_name="Monto inicial de OSP",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bancarización",
                "verbose_name_plural": "Bancarizaciones",
            },
        ),
    ]
